### ISSUE TITLE
Afficher le stockage disponible sur le site

### ISSUE THREAD

**Issue by Walou974** [Swinir/SAE-24_Experimental_XTRA_Photo#41]
### Comment afficher l'espace disponible sur le site ?
**Ce qu'on a besoin pour afficher :**

- **L'espace total du disque** (ou du fichier) contenant les données de la BDD et les photos,

Et :
- soit l'espace utilisé en **Mb/Mo**,
- soit l'espace utilisé en **%**.

Je m'occuperais de modifier le _CSS_ pour l'affichage.

**Comment by nikolenik** [comment]
https://www.php.net/manual/fr/function.disk-free-space.php

**Comment by nikolenik** [comment]
progress bar : https://jsfiddle.net/kimmobrunfeldt/k5v2d0rr/

**Comment by Swinir** [comment]
Fait mais non commité
