### ISSUE TITLE
Vérifier l'approche du stockage et passage des logs au #SW

### ISSUE THREAD

**Issue by Swinir** [Swinir/SAE-24_Experimental_XTRA_Photo#6]
Où seront stockés les logs ?

**Comment by Walou974** [comment]
Les logs coté PHP seront juste stockés dans la BDD (via une requête simple) et puis le programme de @Swinir actualisera dans le fichier .json, je pense. Si besoin, possibilité d'exécuter le script de synchro depuis le PHP.

**Comment by Swinir** [comment]
Les scripts pour synchroniser les logs sont déjà dans la page logs.php normalement

**Comment by Swinir** [comment]
Done : https://github.com/Swinir/SAE-24_Experimental_XTRA_Photo/commit/e3acc2971e8a2863e34ae69a52344a99d3f8084c
